-- Adds a human-readable label column to students. This is display/lookup
-- only, NOT a join key: every FK to students (daily_plan.student_id,
-- check_ins.student_id, achievements.student_id, reward_points.student_id,
-- reward_redemptions.student_id, ai_conversations.student_id) stays uuid
-- and continues referencing students.id. The frontend previously used this
-- text code (format XX2503-48271, generated by generateStudentId.ts) as if
-- it were the join key, causing "invalid input syntax for type uuid" (22P02)
-- on every check-in/daily-plan write. Frontend fixed in the same change to
-- use students.id for joins and this column for the human-readable label.
alter table public.students add column student_id text unique;
